tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/core"
tap "homebrew/services"

brew "bash-completion"
brew "csvkit"
brew "diff-so-fancy"
brew "ffmpeg"
brew "git"
brew "git-quick-stats"
brew "httrack"
brew "hub"
brew "jq"
brew "nmap"
brew "pandoc"
brew "shellcheck"
brew "ssh-audit"
brew "ssllabs-scan"
brew "sslyze"
brew "telnet"
brew "testssl"
brew "tmux"

cask "miniconda"
cask "xquartz"
