tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"

brew "bash-completion"
brew "ccat"
brew "git"
brew "tmux"

cask "airmedia"
cask "atom"
cask "bartender"
cask "google-chrome"
cask "hazel"
cask "microsoft-office"
cask "microsoft-teams"
cask "moom"
cask "mysqlworkbench"
cask "postman"
cask "rocket"
cask "skype-for-business"
cask "stride"
cask "the-unarchiver"
cask "tower"
cask "vagrant"
cask "virtualbox"
cask "zoomus"
